version: "2.1"

services:
  mysql:
    container_name: mysql57
    image: mysql:5.7
    command: mysqld --init-file=/docker-entrypoint-initdb.d/schema.sql --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - ../docker:/docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_ROOT_HOST:
